import type { Template } from '@octolab/domain';

/**
 * List of available templates.
 */
export const availableTemplates: Template[] = [
    {
        id: 'node-pr-verify',
        name: 'Node.js pull request verify',
        description: 'Verify and ensure the quality of pull requests in a Node.js codebase.',
        largeDescription: 'Verify and ensure the quality of pull requests in a Node.js codebase with a production-ready GitHub Actions workflow.',
        icon: 'FaNodeJs',
        iconColor: '#68A063',
        iconLibrary: 'fa',
        features: ['Configurable runners', 'Multiple Node versions', 'Lint and test checks', 'Build verification'],
        steps: ['Checkout', 'Define Node version', 'Install dependencies', 'Lint', 'Test', 'Build'],
        type: 'verification',
        stepCompletionRules: {
            Checkout: { type: 'completed' },
            'Define Node version': { type: 'select-value', key: 'nodeVersion' },
            'Install dependencies': { type: 'non-empty-string', key: 'installCommand' },
            Lint: { type: 'non-empty-string', key: 'lintCommand' },
            Test: { type: 'non-empty-string', key: 'testCommand' },
            Build: { type: 'non-empty-string', key: 'buildCommand' },
        },
        guide: [
            { label: 'Checkout', description: 'Download your repository on the runner' },
            { label: 'Set Node version', description: 'Configure the version of Node.js to be used' },
            { label: 'Install dependencies', description: 'Install the project dependencies' },
            { label: 'Lint', description: 'Check the style and format of the code' },
            { label: 'Tests', description: 'Run tests to validate behavior' },
            { label: 'Build', description: 'Compile and generate distribution artifacts' },
        ],
        whatDoInfo: [
            { label: 'Checkout', description: 'Download your repository on the runner', icon: 'IoDownloadOutline' },
            { label: 'Set Node version', description: 'Configure the version of Node.js to be used', icon: 'IoLogoNodejs' },
            { label: 'Install dependencies', description: 'Install the project dependencies', icon: 'IoConstructOutline' },
            { label: 'Lint', description: 'Check code style and formatting issues.', icon: 'IoSparklesOutline' },
            { label: 'Tests', description: 'Run tests to validate behavior', icon: 'IoBeakerOutline' },
            { label: 'Build', description: 'Compile and generate distribution artifacts', icon: 'IoBuildOutline' },
        ],
        requirements: [
            { description: 'A GitHub repository with a Node.js project and the lint, test, and build scripts configured in package.json.', icon: 'IoLogoGithub' },
            { description: 'Runs on ubuntu-latest. Compatible with public and private repositories.', icon: 'IoServerOutline' },
            { description: 'Possibility to configure Node.js versions 18, 20, and 22.', icon: 'IoLogoNodejs' },
        ],
        faq: [
            { label: 'Can I use pnpm or yarn?', description: 'Yes. Replace the install/test/build commands with your package manager equivalents.', icon: 'IoCubeOutline' },
            {
                label: 'How do I cache dependencies?',
                description: "Add cache: 'npm' under actions/setup-node and a step for restoring/saving cache if needed.",
                icon: 'IoCloudDownloadOutline',
            },
            { label: 'Where should I place this file?', description: 'Save it as .github/workflows/node-pr-verify.yml in your repository.', icon: 'IoDocumentTextOutline' },
            { label: 'Will it run on every PR?', description: 'By default, yes. You can scope branches with on.pull_request.branches.', icon: 'IoGitBranchOutline' },
        ],
    },
    {
        id: 'nx-pr-verify',
        name: 'NX pull request verify',
        description: 'Verify and ensure the quality of pull requests in a monorepo managed with NX.',
        largeDescription:
            'Verify and ensure the quality of pull requests in an NX monorepo using “affected” commands. Only the projects impacted by the PR are linted, tested, and built against a configurable base branch.',
        icon: 'SiNx',
        iconColor: '#143055',
        iconLibrary: 'si',
        features: ['Configurable runners', 'Target branch configuration', 'Affected apps and libs detection', 'Parallelized tasks'],
        steps: ['Checkout', 'Set base branch', 'Define Node version', 'Install dependencies', 'Lint', 'Test', 'Build'],
        type: 'verification',
        stepCompletionRules: {
            Checkout: { type: 'completed' },
            'Set base branch': { type: 'non-empty-string', key: 'baseBranch' },
            'Define Node version': { type: 'select-value', key: 'nodeVersion' },
            'Install dependencies': { type: 'non-empty-string', key: 'installCommand' },
            Lint: { type: 'non-empty-string', key: 'lintCommand' },
            Test: { type: 'non-empty-string', key: 'testCommand' },
            Build: { type: 'non-empty-string', key: 'buildCommand' },
        },
        guide: [
            { label: 'Checkout', description: 'Download your repository on the runner' },
            { label: 'Set base branch', description: 'Configure the base branch for comparison' },
            { label: 'Set Node version', description: 'Configure the version of Node.js to be used' },
            { label: 'Install dependencies', description: 'Install the project dependencies' },
            { label: 'Lint', description: 'Check the style and format of the code' },
            { label: 'Tests', description: 'Run tests to validate behavior' },
            { label: 'Build', description: 'Compile and generate distribution artifacts' },
        ],
        whatDoInfo: [
            { label: 'Checkout', description: 'Download your repository on the runner', icon: 'IoDownloadOutline' },
            { label: 'Set base branch', description: 'Define the base branch to compare and detect affected projects (e.g., main).', icon: 'IoGitBranchOutline' },
            { label: 'Set Node version', description: 'Configure the version of Node.js to be used', icon: 'IoLogoNodejs' },
            { label: 'Install dependencies', description: 'Install the monorepo dependencies', icon: 'IoConstructOutline' },
            { label: 'Lint', description: 'Run lint only for affected apps and libs', icon: 'IoSparklesOutline' },
            { label: 'Tests', description: 'Run tests only for affected apps and libs', icon: 'IoBeakerOutline' },
            { label: 'Build', description: 'Build only the affected apps and libs', icon: 'IoBuildOutline' },
        ],
        requirements: [
            { description: 'A GitHub repository with a Node.js-based NX monorepo project (Nx CLI configured).', icon: 'IoLayersOutline' },
            { description: 'Runs on ubuntu-latest. Compatible with public and private repositories.', icon: 'IoServerOutline' },
            { description: 'Possibility to configure Node.js versions 18, 20, and 22.', icon: 'IoLogoNodejs' },
        ],
        faq: [
            { label: 'Can I use pnpm or yarn?', description: 'Yes. Replace the install/test/build commands with your package manager equivalents.', icon: 'IoCubeOutline' },
            {
                label: 'How do I cache dependencies?',
                description: "Add cache: 'npm' under actions/setup-node and (optionally) use Nx's remote cache if available.",
                icon: 'IoCloudDownloadOutline',
            },
            { label: 'Where should I place this file?', description: 'Save it as .github/workflows/nx-pr-verify.yml in your repository.', icon: 'IoDocumentTextOutline' },
            {
                label: 'Will it run on every PR?',
                description: 'By default, yes. You can scope branches with on.pull_request.branches and adjust the base branch used for affected.',
                icon: 'IoGitBranchOutline',
            },
        ],
    },
    {
        id: 'npm-publish',
        name: 'Publish to NPM',
        description: 'Publish and release packages to NPM automatically after merging.',
        largeDescription:
            'Publish your package to npm automatically when changes are merged into a target branch. This template runs tests and builds first, then authenticates with a secure npm token to perform a clean, production-ready release.',
        icon: 'FaNpm',
        iconColor: '#cb3737',
        iconLibrary: 'fa',
        features: ['Configurable runners', 'Target branch configuration', 'Multiple Node versions', 'Secure NPM authentication'],
        steps: ['Checkout', 'Set destination branch', 'Define Node version', 'Install dependencies', 'Test', 'Build', 'Publish'],
        type: 'distribution',
        stepCompletionRules: {
            Checkout: { type: 'completed' },
            'Set destination branch': { type: 'non-empty-string', key: 'branch' },
            'Define Node version': { type: 'select-value', key: 'nodeVersion' },
            'Install dependencies': { type: 'non-empty-string', key: 'installCommand' },
            Test: { type: 'non-empty-string', key: 'testCommand' },
            Build: { type: 'non-empty-string', key: 'buildCommand' },
            Publish: { type: 'non-empty-string', key: 'npmTokenSecret' },
        },
        guide: [
            { label: 'Checkout', description: 'Download your repository on the runner' },
            { label: 'Set destination branch', description: 'Configures the target branch to push on' },
            { label: 'Set Node version', description: 'Configure the version of Node.js to be used' },
            { label: 'Install dependencies', description: 'Install the project dependencies' },
            { label: 'Tests', description: 'Run tests to validate behavior' },
            { label: 'Build', description: 'Compile and generate distribution artifacts' },
            { label: 'Set NPM options', description: 'Configure NPM credentials to publish the artifact' },
        ],
        whatDoInfo: [
            { label: 'Checkout', description: 'Download your repository on the runner', icon: 'IoDownloadOutline' },
            { label: 'Set destination branch', description: 'Select the branch that will trigger publishing (e.g., main).', icon: 'IoGitBranchOutline' },
            { label: 'Define Node version', description: 'Configure the version of Node.js to be used', icon: 'IoLogoNodejs' },
            { label: 'Install dependencies', description: 'Install the project dependencies', icon: 'IoConstructOutline' },
            { label: 'Test', description: 'Run tests to validate behavior before publishing', icon: 'IoBeakerOutline' },
            { label: 'Build', description: 'Compile and prepare distribution artifacts', icon: 'IoBuildOutline' },
            { label: 'Publish', description: 'Authenticate with npm and publish the package to the registry', icon: 'IoCloudUploadOutline' },
        ],
        requirements: [
            { description: 'A GitHub repository with a Node.js package (package.json with name and version) and test/build scripts.', icon: 'IoLogoGithub' },
            { description: 'An npm Automation Token stored as a repository secret (e.g., NPM_TOKEN) with publish permissions.', icon: 'IoKeyOutline' },
            { description: 'Runner on ubuntu-latest. Compatible with public and private repositories.', icon: 'IoServerOutline' },
            { description: 'Support for Node.js versions 18, 20, and 22.', icon: 'IoLogoNodejs' },
        ],
        faq: [
            {
                label: 'How do I provide the npm token?',
                description:
                    'Create an npm Automation Token and add it as a repo secret (e.g., NPM_TOKEN). The workflow uses JS-DevTools/npm-publish@v3 with the npm registry to authenticate.',
                icon: 'IoKeyOutline',
            },
            {
                label: 'What about 2FA on npm?',
                description: 'Use an npm Automation Token. It bypasses interactive 2FA for CI while keeping your account secure.',
                // eslint-disable-next-line no-secrets/no-secrets
                icon: 'IoShieldCheckmarkOutline',
            },
            {
                label: 'Will it publish on every push?',
                description: 'No, only when the configured destination branch triggers the workflow (e.g., merges to main). Adjust the branch filter to change this behavior.',
                icon: 'IoGitBranchOutline',
            },
            {
                label: 'Can I use pnpm or yarn?',
                description:
                    'Yes. Replace install/test/build commands with your package manager equivalents. Publishing can be done via npm or your chosen tool’s publish command.',
                icon: 'IoCubeOutline',
            },
        ],
    },
    {
        id: 'vercel-pro-deployment',
        name: 'Vercel production deployment',
        description: 'Deploy an application to Vercel in production environment.',
        largeDescription: 'Deploy your application to a Vercel production environment from GitHub Actions.',
        icon: 'IoLogoVercel',
        iconColor: '#000000',
        iconLibrary: 'io5',
        features: ['Configurable runners', 'Target branch configuration', 'Sync environment and secrets from Vercel', 'Prebuilt artifact deployment'],
        steps: ['Checkout', 'Set destination branch', 'Install Vercel CLI', 'Build', 'Deploy'],
        type: 'deployment',
        stepCompletionRules: {
            Checkout: { type: 'completed' },
            'Set destination branch': { type: 'non-empty-string', key: 'branch' },
            'Install Vercel CLI': { type: 'completed' },
            Build: { type: 'non-empty-string', key: 'vercelTokenSecret' },
            Deploy: { type: 'non-empty-string', key: 'vercelTokenSecret' },
        },
        guide: [
            { label: 'Checkout', description: 'Download your repository on the runner' },
            { label: 'Set destination branch', description: 'Configures the target branch to push on' },
            { label: 'Install Vercel CLI', description: 'Install the Vercel CLI globally in the runner' },
            { label: 'Pull Vercel environment', description: 'Synchronize your project’s configuration from Vercel' },
            { label: 'Build', description: 'Build the project locally' },
            { label: 'Deploy', description: 'Deploy the prebuilt output to Vercel production environment' },
        ],
        whatDoInfo: [
            { label: 'Checkout', description: 'Download your repository on the runner', icon: 'IoDownloadOutline' },
            { label: 'Set destination branch', description: 'Select the branch that will trigger the Production deploy (e.g., main).', icon: 'IoGitBranchOutline' },
            { label: 'Install Vercel CLI', description: 'Install the Vercel CLI globally in the runner', icon: 'IoTerminalOutline' },
            { label: 'Pull Vercel environment', description: 'Sync project settings and environment variables from Vercel', icon: 'IoSyncOutline' },
            { label: 'Build', description: 'Create a local production build (prebuilt output)', icon: 'IoBuildOutline' },
            { label: 'Deploy', description: 'Deploy the prebuilt output to Vercel Production using the CLI', icon: 'IoCloudUploadOutline' },
        ],
        requirements: [
            { description: 'A GitHub repository linked to a Vercel project.', icon: 'IoLinkOutline' },
            { description: 'A Vercel token stored as a repository secret (e.g., VERCEL_TOKEN) with deploy permissions.', icon: 'IoKeyOutline' },
            { description: 'If the repository isn’t already linked, provide VERCEL_ORG_ID and VERCEL_PROJECT_ID as environment variables.', icon: 'IoSettingsOutline' },
            { description: 'Runs on ubuntu-latest runner.', icon: 'IoServerOutline' },
        ],
        faq: [
            {
                label: 'How do I provide the Vercel token?',
                description: 'Create a token in your Vercel account settings and add it as a repository secret. The workflow authenticates the CLI with this token.',
                icon: 'IoKeyOutline',
            },
            {
                label: 'How are project settings and env vars pulled?',
                description: 'The workflow runs `vercel pull` (production) with your token to sync project configuration and environment variables.',
                icon: 'IoSyncOutline',
            },
            {
                label: 'Does this create a Production or a Preview deployment?',
                description: 'The CLI deploy step uses the Production target. Switch to Preview by removing the Production flag in the deploy step.',
                icon: 'IoCloudUploadOutline',
            },
            {
                label: 'Will it deploy on every push?',
                description:
                    'No. It only deploys when the configured destination branch triggers the workflow (e.g., pushes to main). Adjust the branch filter to change this behavior.',
                icon: 'IoGitBranchOutline',
            },
        ],
    },
    {
        id: 'semantic-release',
        name: 'Releasing with Semantic Release',
        description: 'Automate versioning, changelog generation and release generation on every push.',
        largeDescription: '',
        icon: 'FaRobot',
        iconColor: '#40a9ff',
        iconLibrary: 'fa',
        features: ['Configurable runners', 'Target branch configuration', 'Multiple Node versions', 'Automated versioning and changelog'],
        steps: ['Checkout', 'Set destination branch', 'Define Node version', 'Install dependencies', 'Build', 'Launch Semantic Release'],
        type: 'releasing',
        stepCompletionRules: {
            Checkout: { type: 'completed' },
            'Set destination branch': { type: 'non-empty-string', key: 'branch' },
            'Define Node version': { type: 'select-value', key: 'nodeVersion' },
            'Install dependencies': { type: 'non-empty-string', key: 'installCommand' },
            Build: { type: 'non-empty-string', key: 'buildCommand' },
            'Launch Semantic Release': { type: 'non-empty-string', keys: ['releaseCommand', 'githubTokenSecret'] },
        },
        guide: [
            { label: 'Checkout', description: 'Download your repository on the runner' },
            { label: 'Set destination branch', description: 'Configure the target branch to trigger the release' },
            { label: 'Set Node version', description: 'Configure the version of Node.js to be used' },
            { label: 'Install dependencies', description: 'Install the project dependencies' },
            { label: 'Build', description: 'Compile and generate distribution artifacts' },
            { label: 'Launch Semantic Release', description: 'Run the Semantic Release CLI to publish the release' },
        ],
        whatDoInfo: [],
        requirements: [],
        faq: [],
    },
    {
        id: 'aws-s3-cloudfront-deploy',
        name: 'Deploy to AWS S3 and CloudFront',
        description: 'Automate deployments to AWS for modern static or frontend applications.',
        largeDescription: '',
        icon: 'FaAws',
        iconColor: '#FF9900',
        iconLibrary: 'fa',
        features: ['Configurable runners', 'Target branch configuration', 'Secure AWS authentication with IAM roles', 'Automatic CloudFront cache invalidation'],
        steps: ['Checkout', 'Set destination branch', 'Define Node version', 'Install dependencies', 'Build', 'Set AWS configuration'],
        type: 'deployment',
        stepCompletionRules: {
            Checkout: { type: 'completed' },
            'Set destination branch': { type: 'non-empty-string', key: 'branch' },
            'Define Node version': { type: 'select-value', key: 'nodeVersion' },
            'Install dependencies': { type: 'non-empty-string', key: 'installCommand' },
            'Set AWS configuration': {
                type: 'non-empty-string',
                keys: [
                    'awsRegionEnvironmentVariable',
                    'awsRegionEnvironmentVariableValue',
                    'awsRoleNameEnvironmentVariable',
                    'awsRoleNameEnvironmentVariableValue',
                    // eslint-disable-next-line no-secrets/no-secrets
                    'awsS3BucketEnvironmentVariable',
                    // eslint-disable-next-line no-secrets/no-secrets
                    'awsS3BucketEnvironmentVariableValue',
                    'sourceDirEnvironmentVariable',
                    'sourceDirEnvironmentVariableValue',
                    'cloudfrontDistributionIdSecret',
                    'awsAccountIdSecret',
                ],
            },
            Build: { type: 'non-empty-string', key: 'buildCommand' },
        },
        guide: [
            { label: 'Checkout', description: 'Download your repository on the runner' },
            { label: 'Set destination branch', description: 'Configure the target branch to deploy from' },
            { label: 'Set Node version', description: 'Configure the version of Node.js to be used' },
            { label: 'Install dependencies', description: 'Install the project dependencies' },
            { label: 'Build', description: 'Compile and generate distribution artifacts' },
            { label: 'Set AWS configuration', description: 'Configure credentials and deploy files to S3 and invalidate CloudFront cache' },
        ],
        whatDoInfo: [],
        requirements: [],
        faq: [],
    },
    {
        id: 'security-scan-snyk',
        name: 'Security scan with Snyk',
        description: 'Scans dependencies for vulnerabilities for different types of code using Snyk.',
        largeDescription: '',
        icon: 'SiSnyk',
        iconColor: '#999999',
        iconLibrary: 'si',
        features: ['Configurable runners', 'Target branch configuration', 'Code stack selection', 'Configurable vulnerability criticality'],
        steps: ['Checkout', 'Set destination branch', 'Set stack', 'Set severity threshold', 'Run Snyk scan'],
        type: 'security',
        stepCompletionRules: {
            Checkout: { type: 'completed' },
            'Set destination branch': { type: 'non-empty-string', key: 'branch' },
            'Set stack': { type: 'select-value', key: 'snykCodeStack' },
            'Set severity threshold': { type: 'select-value', key: 'snykSeverityThreshold' },
            'Run Snyk scan': { type: 'non-empty-string', key: 'snykTokenSecret' },
        },
        guide: [
            { label: 'Checkout', description: 'Download your repository on the runner' },
            { label: 'Set destination branch', description: 'Configure the target branch to scan from' },
            { label: 'Set stack', description: 'Specify the type of code to scan (e.g., Node, Java, Python)' },
            { label: 'Set severity threshold', description: 'Define the minimum vulnerability level to fail the scan' },
            { label: 'Run Snyk scan', description: 'Execute Snyk CLI to detect vulnerabilities using the configured token' },
        ],
        whatDoInfo: [],
        requirements: [],
        faq: [],
    },
    {
        id: 'docker-image-publish',
        name: 'Publish Docker image',
        description: 'Build and publish Docker images automatically to a container registry after merging.',
        largeDescription: '',
        icon: 'FaDocker',
        iconColor: '#2496ED',
        iconLibrary: 'fa',
        features: ['Configurable runners', 'Target branch configuration', 'Support for multiple registries', 'Custom tagging and versioning'],
        steps: ['Set destination branch', 'Set registry', 'Set credentials', 'Set build context'],
        type: 'distribution',
        stepCompletionRules: {
            'Set destination branch': { type: 'non-empty-string', key: 'branch' },
            'Set registry': { type: 'select-value', key: 'dockerRegistry' },
            'Set credentials': { type: 'non-empty-string', keys: ['dockerUsername', 'dockerPasswordSecret'] },
            'Set build context': { type: 'non-empty-string', keys: ['dockerBuildContext', 'dockerDockerfile', 'dockerImageTags'] },
        },
        guide: [
            { label: 'Set destination branch', description: 'Configure the target branch to publish from' },
            { label: 'Set registry', description: 'Select the container registry to push the image to' },
            { label: 'Set credentials', description: 'Configure authentication using registry username and secret' },
            { label: 'Set build context', description: 'Define the Dockerfile path, build context, and image tags' },
        ],
        whatDoInfo: [],
        requirements: [],
        faq: [],
    },
    {
        id: 'auto-tag-version',
        name: 'Auto tag on version change',
        description: 'Detects version changes and creates a Git tag automatically based on your version file.',
        largeDescription: '',
        icon: 'FaTag',
        iconColor: '#f59e0b',
        iconLibrary: 'fa',
        features: [
            'Detects changes in package.json or custom version files',
            'Automatically creates a tag (e.g. v1.2.3)',
            'Customizable tag templates',
            'Useful for manual versioning flows without full release tooling',
        ],
        steps: ['Checkout', 'Set Auto Tag command'],
        type: 'versioning',
        stepCompletionRules: {
            Checkout: { type: 'completed' },
            'Set Auto Tag command': { type: 'non-empty-string', key: 'autoTagVersionCommand' },
        },
        guide: [
            { label: 'Checkout', description: 'Download your repository on the runner' },
            { label: 'Set Auto Tag command', description: 'Configure the command to detect version changes and create the Git tag' },
        ],
        whatDoInfo: [],
        requirements: [],
        faq: [],
    },
    {
        id: 'laravel-forge-deploy',
        name: 'Laravel Forge deployment',
        description: 'Deploy a Laravel application to a Laravel Forge-managed server on push events.',
        largeDescription: '',
        icon: 'FaLaravel',
        iconColor: '#ff2d20',
        iconLibrary: 'fa',
        features: ['Deploy via Forge trigger Url or API', 'Configurable runners', 'Target branch configuration', 'Supports zero-downtime Laravel deployments'],
        steps: ['Checkout', 'Set destination branch', 'Set deployment mode', 'Set Forge configuration'],
        type: 'deployment',
        stepCompletionRules: {
            Checkout: { type: 'completed' },
            'Set destination branch': { type: 'non-empty-string', key: 'branch' },
            'Set deployment mode': { type: 'select-value', key: 'deployMode' },
            'Set Forge configuration': {
                type: 'non-empty-string',
                keys: [
                    'laravelForgeDeployTriggerUrlSecretName',
                    'laravelForgeDeployApiKeySecretName',
                    'laravelForgeDeployServerIdSecretName',
                    'laravelForgeDeploySiteIdSecretName',
                ],
            },
        },
        guide: [
            { label: 'Checkout', description: 'Download your repository on the runner' },
            { label: 'Set destination branch', description: 'Configure the target branch to deploy from' },
            { label: 'Set deployment mode', description: 'Select whether to deploy via trigger URL or API key' },
            { label: 'Set Forge configuration', description: 'Configure secrets and identifiers required for the Laravel Forge deployment' },
        ],
        whatDoInfo: [],
        requirements: [],
        faq: [],
    },
    {
        id: 'pr-conventional-commit-checker',
        name: 'Pull Request Conventional Commit checker',
        description: 'Ensure all commits in pull requests follow the Conventional Commits specification.',
        largeDescription: '',
        icon: 'IoGitCommit',
        iconColor: '#22c55e',
        iconLibrary: 'io5',
        features: ['Configurable runners', 'Supports multiple target branches', 'Validates commits on pull requests', 'Configurable validation pattern'],
        steps: ['Checkout', 'Configure branches', 'Set commit patterns'],
        type: 'verification',
        stepCompletionRules: {
            Checkout: { type: 'completed' },
            'Configure branches': { type: 'non-empty-string', keys: ['currentBranch', 'targetBranch'] },
            'Set commit patterns': { type: 'non-empty-string', key: 'commitLintPattern' },
        },
        guide: [
            { label: 'Checkout', description: 'Download your repository and full commit history' },
            { label: 'Configure action', description: 'Set the current and target branches and define patterts for the commit check' },
            { label: 'Run checker', description: 'Run the commit checker with a pattern matching Conventional Commits' },
        ],
        whatDoInfo: [],
        requirements: [],
        faq: [],
    },
];
