import type { Template } from '@octolab/domain';

/**
 * List of available templates.
 */
export const availableTemplates: Template[] = [
    {
        id: 'node-pr-verify',
        name: 'Node.js pull request verify',
        description: 'Verify and ensure the quality of pull requests in a Node.js codebase.',
        icon: 'FaNodeJs',
        iconColor: '#68A063',
        iconLibrary: 'fa',
        features: ['Configurable runners', 'Multiple Node versions', 'Lint and test checks', 'Build verification'],
        type: 'verification',
    },
    {
        id: 'nx-pr-verify',
        name: 'NX pull request verify',
        description: 'Verify and ensure the quality of pull requests in a monorepo managed with NX.',
        icon: 'SiNx',
        iconColor: '#143055',
        iconLibrary: 'si',
        features: ['Configurable runners', 'Target branch configuration', 'Affected apps and libs detection', 'Parallelized tasks'],
        type: 'verification',
    },
    {
        id: 'npm-publish',
        name: 'Publish to NPM',
        description: 'Publish and release packages to NPM automatically after merging.',
        icon: 'FaNpm',
        iconColor: '#cb3737',
        iconLibrary: 'fa',
        features: ['Configurable runners', 'Target branch configuration', 'Multiple Node versions', 'Secure NPM authentication'],
        type: 'distribution',
    },
    {
        id: 'vercel-pro-deployment',
        name: 'Vercel production deployment',
        description: 'Deploy an application to Vercel in production environment.',
        icon: 'IoLogoVercel',
        iconColor: '#000000',
        iconLibrary: 'io5',
        features: ['Configurable runners', 'Target branch configuration', 'Sync environment and secrets from Vercel', 'Prebuilt artifact deployment'],
        type: 'deployment',
    },
    {
        id: 'semantic-release',
        name: 'Releasing with Semantic Release',
        description: 'Automate versioning, changelog generation and release generation on every push.',
        icon: 'FaRobot',
        iconColor: '#40a9ff',
        iconLibrary: 'fa',
        features: ['Configurable runners', 'Target branch configuration', 'Multiple Node versions', 'Automated versioning and changelog'],
        type: 'releasing',
    },
    {
        id: 'aws-s3-cloudfront-deploy',
        name: 'Deploy to AWS S3 and CloudFront',
        description: 'Automate deployments to AWS for modern static or frontend applications.',
        icon: 'FaAws',
        iconColor: '#FF9900',
        iconLibrary: 'fa',
        features: ['Configurable runners', 'Target branch configuration', 'Secure AWS authentication with IAM roles', 'Automatic CloudFront cache invalidation'],
        type: 'deployment',
    },
    {
        id: 'security-scan-snyk',
        name: 'Security scan with Snyk',
        description: 'Scans dependencies for vulnerabilities for different types of code using Snyk.',
        icon: 'SiSnyk',
        iconColor: '#999999',
        iconLibrary: 'si',
        features: ['Configurable runners', 'Target branch configuration', 'Code stack selection', 'Configurable vulnerability criticality'],
        type: 'security',
    },
    {
        id: 'docker-image-publish',
        name: 'Publish Docker image',
        description: 'Build and publish Docker images automatically to a container registry after merging.',
        icon: 'FaDocker',
        iconColor: '#2496ED',
        iconLibrary: 'fa',
        features: ['Configurable runners', 'Target branch configuration', 'Support for multiple registries', 'Custom tagging and versioning'],
        type: 'distribution',
    },
    {
        id: 'auto-tag-version',
        name: 'Auto tag on version change',
        description: 'Detects version changes and creates a Git tag automatically based on your version file.',
        icon: 'FaTag',
        iconColor: '#f59e0b',
        iconLibrary: 'fa',
        features: [
            'Detects changes in package.json or custom version files',
            'Automatically creates a tag (e.g. v1.2.3)',
            'Customizable tag templates',
            'Useful for manual versioning flows without full release tooling',
        ],
        type: 'versioning',
    },
];
