packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@sentry/cli': true
  esbuild: true
  sharp: false
  unrs-resolver: true

overrides:
  '@gitopslovers/eslint-config-multistack': link:../eslint-config-multistack
