packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@sentry/cli': true
  esbuild: true
  sharp: false
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@gitopslovers/eslint-config-multistack@1.6.0'
