import { Action } from '@octolab/domain';

/**
 * List of available workflow actions
 */
export const workflowsActions: Action[] = [
    {
        id: 'actions/checkout@v4',
        inputs: [
            {
                key: 'fetch-depth',
                label: 'Fetch depth',
                placeholder: '0',
                required: false,
                type: 'number',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
            },
        ],
    },
    {
        id: 'actions/setup-node@v4',
        inputs: [
            {
                key: 'node-version',
                label: 'Node version',
                placeholder: '18',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
            },
        ],
    },
    {
        id: 'JS-DevTools/npm-publish@v3',
        inputs: [
            {
                key: 'token',
                label: 'NPM Token Secret Name',
                placeholder: 'NPM_TOKEN',
                required: true,
                type: 'string',
                isSecret: true,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
            },
        ],
    },
    {
        id: 'aws-actions/configure-aws-credentials@v4',
        inputs: [
            {
                key: 'role-to-assume',
                label: 'AWS account ID secret name',
                placeholder: 'AWS_ACCOUNT_ID',
                required: true,
                type: 'string',
                isSecret: true,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
            },
            {
                key: 'aws-region',
                label: 'AWS region environment variable name',
                placeholder: 'MY_AWS_REGION',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: true,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
            },
            {
                key: 'aws-region-env-value',
                label: 'AWS region environment variable value',
                placeholder: '<YOUR AWS REGION>',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: true,
                hideInForm: false,
            },
            {
                key: 'aws-rolename',
                label: 'AWS role name environment variable name',
                placeholder: 'AWS_ROLENAME',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: true,
                isStepEnvironmentVariable: false,
                hideInYaml: true,
                hideInForm: false,
            },
            {
                key: 'aws-rolename-env-value',
                label: 'AWS role name environment variable value',
                placeholder: '<YOUR AWS ROLE>',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: true,
                isStepEnvironmentVariable: false,
                hideInYaml: true,
                hideInForm: false,
            },
        ],
        templates: {
            'role-to-assume': 'arn:aws:iam::${{ secrets.{role-to-assume} }}:role/${{ env.{aws-rolename} }}',
        },
    },
    {
        id: 'snyk/actions/node@master',
        inputs: [
            {
                key: 'args',
                label: 'Severity threshold',
                placeholder: '',
                required: true,
                type: 'select',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
                options: [
                    { label: 'Low', value: 'low' },
                    { label: 'Medium', value: 'medium' },
                    { label: 'High', value: 'high' },
                ],
            },
            {
                key: 'snyk-token',
                label: 'Snyk token secret name',
                placeholder: 'SNYK_TOKEN',
                required: true,
                type: 'string',
                isSecret: true,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: true,
                hideInYaml: false,
                hideInForm: false,
            },
        ],
        templates: {
            args: '--severity-threshold={args}',
        },
    },
    {
        id: 'docker/login-action@v3',
        inputs: [
            {
                key: 'username',
                label: 'Docker Hub username',
                placeholder: '<YOUR_DOCKER_USERNAME>',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
            },
            {
                key: 'password',
                label: 'Docker Hub password secret name',
                placeholder: 'DOCKER_PASSWORD',
                required: true,
                type: 'string',
                isSecret: true,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
            },
        ],
    },
    {
        id: 'docker/setup-qemu-action@v3',
        inputs: [],
    },
    {
        id: 'docker/setup-buildx-action@v3',
        inputs: [],
    },
    {
        id: 'docker/build-push-action@v6',
        inputs: [
            {
                key: 'context',
                label: 'Docker build context',
                placeholder: '.',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
            },
            {
                key: 'file',
                label: 'Dockerfile',
                placeholder: 'Dockerfile',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
            },
            {
                key: 'push',
                label: '',
                placeholder: '',
                required: true,
                type: 'boolean',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: true,
                defaultValue: true,
            },
            {
                key: 'tags',
                label: 'Docker image tags (comma separated)',
                placeholder: 'latest',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
            },
        ],
    },
];
