import { Action } from '@octolab/domain';

/**
 * List of available workflow actions
 */
export const workflowsActions: Action[] = [
    {
        id: 'actions/checkout@v4',
        inputs: [
            {
                key: 'fetch-depth',
                label: 'Fetch depth',
                placeholder: '0',
                required: false,
                type: 'number',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
                info: 'Fetch depth of the git repository. 0 means full history.',
                defaultValue: 0,
            },
        ],
    },
    {
        id: 'actions/setup-node@v4',
        inputs: [
            {
                key: 'node-version',
                label: 'Node version',
                placeholder: '18',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
                info: 'Node.js version to use. Can be a specific version or a range (e.g., 18.x).',
                defaultValue: '18',
            },
        ],
    },
    {
        id: 'JS-DevTools/npm-publish@v3',
        inputs: [
            {
                key: 'token',
                label: 'NPM Token Secret Name',
                placeholder: 'NPM_TOKEN',
                required: true,
                type: 'string',
                isSecret: true,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
                info: 'The secret name for the NPM token used for authentication.',
                defaultValue: 'NPM_TOKEN',
            },
        ],
    },
    {
        id: 'aws-actions/configure-aws-credentials@v4',
        inputs: [
            {
                key: 'role-to-assume',
                label: 'AWS account ID secret name',
                placeholder: 'AWS_ACCOUNT_ID',
                required: true,
                type: 'string',
                isSecret: true,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
                info: 'The secret name for the AWS account ID to assume the role in.',
                defaultValue: 'AWS_ACCOUNT_ID',
            },
            {
                key: 'aws-region',
                label: 'AWS region environment variable name',
                placeholder: 'MY_AWS_REGION',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: true,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
                info: 'The environment variable name for the AWS region to use.',
                defaultValue: 'MY_AWS_REGION',
            },
            {
                key: 'aws-region-env-value',
                label: 'AWS region environment variable value',
                placeholder: '<YOUR AWS REGION>',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: true,
                hideInForm: false,
                info: 'The value for the AWS region environment variable.',
                defaultValue: 'cn-northwest-1',
            },
            {
                key: 'aws-rolename',
                label: 'AWS role name environment variable name',
                placeholder: 'AWS_ROLENAME',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: true,
                isStepEnvironmentVariable: false,
                hideInYaml: true,
                hideInForm: false,
                info: 'The environment variable name for the AWS role name to assume.',
            },
            {
                key: 'aws-rolename-env-value',
                label: 'AWS role name environment variable value',
                placeholder: '<YOUR AWS ROLE>',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: true,
                isStepEnvironmentVariable: false,
                hideInYaml: true,
                hideInForm: false,
                info: 'The value for the AWS role name environment variable.',
            },
        ],
        templates: {
            'role-to-assume': 'arn:aws:iam::${{ secrets.{role-to-assume} }}:role/${{ env.{aws-rolename} }}',
        },
    },
    {
        id: 'snyk/actions/node@master',
        inputs: [
            {
                key: 'args',
                label: 'Severity threshold',
                placeholder: '',
                required: true,
                type: 'select',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
                options: [
                    { label: 'Low', value: 'low' },
                    { label: 'Medium', value: 'medium' },
                    { label: 'High', value: 'high' },
                ],
                info: 'The severity threshold for the Snyk scan. Choose from Low, Medium, or High.',
                defaultValue: 'medium',
            },
            {
                key: 'snyk-token',
                label: 'Snyk token secret name',
                placeholder: 'SNYK_TOKEN',
                required: true,
                type: 'string',
                isSecret: true,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: true,
                hideInYaml: false,
                hideInForm: false,
                info: 'The secret name for the Snyk token used for authentication.',
                defaultValue: 'SNYK_TOKEN',
            },
        ],
        templates: {
            args: '--severity-threshold={args}',
        },
    },
    {
        id: 'docker/login-action@v3',
        inputs: [
            {
                key: 'username',
                label: 'Docker Hub username',
                placeholder: '<YOUR_DOCKER_USERNAME>',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
                info: 'Your Docker Hub username for authentication.',
                defaultValue: 'my-docker-username',
            },
            {
                key: 'password',
                label: 'Docker Hub password secret name',
                placeholder: 'DOCKER_PASSWORD',
                required: true,
                type: 'string',
                isSecret: true,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
                info: 'The secret name for your Docker Hub password used for authentication.',
                defaultValue: 'DOCKER_PASSWORD',
            },
        ],
    },
    {
        id: 'docker/setup-qemu-action@v3',
        inputs: [],
    },
    {
        id: 'docker/setup-buildx-action@v3',
        inputs: [],
    },
    {
        id: 'docker/build-push-action@v6',
        inputs: [
            {
                key: 'context',
                label: 'Docker build context',
                placeholder: '.',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
                info: 'The context for the Docker build. Typically the root of your repository.',
                defaultValue: '.',
            },
            {
                key: 'file',
                label: 'Dockerfile',
                placeholder: 'Dockerfile',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
                info: 'The path to the Dockerfile to use for the build.',
                defaultValue: 'Dockerfile',
            },
            {
                key: 'push',
                label: '',
                placeholder: '',
                required: true,
                type: 'boolean',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: true,
                defaultValue: true,
                info: 'Whether to push the built image to the Docker registry.',
            },
            {
                key: 'tags',
                label: 'Docker image tags (comma separated)',
                placeholder: 'latest',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
                info: 'Comma-separated list of tags for the Docker image. For example: "latest,1.0.0".',
                defaultValue: 'latest',
            },
        ],
    },
    {
        id: 'jbrooksuk/laravel-forge-action@v1.0.2',
        inputs: [
            {
                key: 'deployMode',
                label: 'Deployment mode',
                placeholder: '',
                required: true,
                type: 'select',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: true,
                hideInForm: false,
                options: [
                    { label: 'Webhook', value: 'webhook' },
                    { label: 'API', value: 'api' },
                ],
                info: 'Select whether to deploy via trigger URL or API key',
            },
            {
                key: 'api_key',
                label: 'API Key secret name',
                placeholder: 'LARAVEL_FORGE_API_KEY',
                required: true,
                type: 'string',
                isSecret: true,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: true,
                info: 'The secret name for your Laravel Forge API key.',
                showWhen: { field: 'deployMode', op: 'equals', value: 'webhook' },
                defaultValue: 'LARAVEL_FORGE_API_KEY',
            },
            {
                key: 'server_id',
                label: 'Server ID secret name',
                placeholder: 'LARAVEL_FORGE_SERVER_ID',
                required: true,
                type: 'string',
                isSecret: true,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: true,
                info: 'The secret name for your Laravel Forge server ID.',
                showWhen: { field: 'deployMode', op: 'equals', value: 'api' },
                defaultValue: 'LARAVEL_FORGE_SERVER_ID',
            },
            {
                key: 'site_id',
                label: 'Site ID secret name',
                placeholder: 'LARAVEL_FORGE_SITE_ID',
                required: true,
                type: 'string',
                isSecret: true,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: true,
                info: 'The secret name for your Laravel Forge site ID.',
                showWhen: { field: 'deployMode', op: 'equals', value: 'api' },
                defaultValue: 'LARAVEL_FORGE_SITE_ID',
            },
        ],
    },
    {
        id: 'netodevel/conventional-commits-checker@v1.0.1',
        inputs: [
            {
                key: 'target-branch',
                label: 'Target branch',
                placeholder: '${{ github.event.pull_request.base.ref }}',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
                info: 'The branch into which the pull request is being merged.',
                defaultValue: '${{ github.event.pull_request.base.ref }}',
            },
            {
                key: 'current-branch',
                label: 'Current branch',
                placeholder: '${{ github.event.pull_request.head.ref }}',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
                info: 'The branch from which the pull request originates.',
                defaultValue: '${{ github.event.pull_request.head.ref }}',
            },
            {
                key: 'commit-lint-pattern',
                label: 'Commit lint pattern',
                placeholder: '(feat|fix|ci|chore|docs|test|style|refactor): .{1,}$',
                required: true,
                type: 'string',
                isSecret: false,
                isEnvironmentVariable: false,
                isStepEnvironmentVariable: false,
                hideInYaml: false,
                hideInForm: false,
                info: 'Regular expression to validate commit messages',
                defaultValue: '(feat|fix|ci|chore|docs|test|style|refactor): .{1,}$',
            },
        ],
    },
];
