import { WorkflowTemplateConfig } from '@octolab/domain';

/**
 * Default configurations for template workflows.
 */
export const workflowsDefaultConfigs: Record<string, WorkflowTemplateConfig> = {
    'node-pr-verify': {
        id: 'node-pr-verify',
        runner: 'ubuntu-latest',
        jobName: 'verify',
        name: 'Node.js pull request verify',
        description: 'Workflow to check the quality of a pull request in a Node.js stack.',
        filename: 'node-pr-verify.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'Node.js pull request verify',
                required: true,
                value: 'Node.js pull request verify',
            },
            {
                key: 'nodeVersion',
                label: 'Node.js version',
                type: 'select',
                required: true,
                options: ['16', '18', '20', '22'],
                default: '22',
                value: '22',
            },
            {
                key: 'installCommand',
                label: 'Install command',
                type: 'input',
                placeholder: 'npm install',
                required: true,
                value: 'npm install',
            },
            {
                key: 'lintCommand',
                label: 'Lint command',
                type: 'input',
                placeholder: 'npm run lint',
                required: true,
                value: 'npm run lint',
            },
            {
                key: 'testCommand',
                label: 'Test command',
                type: 'input',
                placeholder: 'npm run test',
                required: true,
                value: 'npm run test',
            },
            {
                key: 'buildCommand',
                label: 'Build command',
                type: 'input',
                placeholder: 'npm run build',
                required: true,
                value: 'npm run build',
            },
        ],
    },
    'nx-pr-verify': {
        id: 'nx-pr-verify',
        runner: 'ubuntu-latest',
        jobName: 'verify',
        name: 'NX pull request verify',
        description: 'Workflow to check the quality of a pull request in a NX monorepo.',
        filename: 'nx-pr-verify.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'NX Pull request verify',
                required: true,
                value: 'NX Pull request verify',
            },
            {
                key: 'baseBranch',
                label: 'Base branch',
                type: 'input',
                placeholder: 'main',
                required: true,
                value: 'main',
            },
            {
                key: 'nodeVersion',
                label: 'Node.js version',
                type: 'select',
                required: true,
                options: ['16', '18', '20', '22'],
                default: '22',
                value: '22',
            },
            {
                key: 'installCommand',
                label: 'Install command',
                type: 'input',
                placeholder: 'npm install',
                required: true,
                value: 'npm install',
            },
            {
                key: 'lintCommand',
                label: 'Lint command',
                type: 'input',
                placeholder: 'npx nx affected --target=lint --head=HEAD',
                required: true,
                value: 'npx nx affected --target=lint --head=HEAD',
            },
            {
                key: 'testCommand',
                label: 'Test command',
                type: 'input',
                placeholder: 'npx nx affected --target=test --head=HEAD',
                required: true,
                value: 'npx nx affected --target=test --head=HEAD',
            },
            {
                key: 'buildCommand',
                label: 'Build command',
                type: 'input',
                placeholder: 'npx nx affected --target=build --head=HEAD',
                required: true,
                value: 'npx nx affected --target=build --head=HEAD',
            },
        ],
    },
    'npm-publish': {
        id: 'npm-publish',
        runner: 'ubuntu-latest',
        jobName: 'publish',
        name: 'Publish to NPM',
        description: 'Workflow to publish a package in NPM.',
        filename: 'npm-publish.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'Publish to NPM',
                required: true,
                value: 'Publish to NPM',
            },
            {
                key: 'branch',
                label: 'Branch',
                type: 'input',
                placeholder: 'main',
                required: true,
                value: 'main',
            },
            {
                key: 'nodeVersion',
                label: 'Node.js version',
                type: 'select',
                required: true,
                options: ['16', '18', '20', '22'],
                default: '22',
                value: '22',
            },
            {
                key: 'installCommand',
                label: 'Install command',
                type: 'input',
                placeholder: 'npm install',
                required: true,
                value: 'npm install',
            },
            {
                key: 'testCommand',
                label: 'Test command',
                type: 'input',
                placeholder: 'npm run test',
                required: true,
                value: 'npm run test',
            },
            {
                key: 'buildCommand',
                label: 'Build command',
                type: 'input',
                placeholder: 'npm run build',
                required: true,
                value: 'npm run build',
            },
            {
                key: 'npmTokenSecret',
                label: 'NPM token secret name',
                type: 'input',
                placeholder: 'NPM_TOKEN',
                required: true,
                value: 'NPM_TOKEN',
            },
        ],
    },
    'vercel-pro-deployment': {
        id: 'vercel-pro-deployment',
        runner: 'ubuntu-latest',
        jobName: 'deploy',
        name: 'Vercel production deployment',
        description: 'Deploy a productive application to Vercel',
        filename: 'vercel-pro-deployment.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'Vercel PRO deployment',
                required: true,
                value: 'Vercel PRO deployment',
            },
            {
                key: 'branch',
                label: 'Branch',
                type: 'input',
                placeholder: 'main',
                required: true,
                value: 'main',
            },
            {
                key: 'vercelTokenSecret',
                label: 'Vercel token secret name',
                type: 'input',
                placeholder: 'VERCEL_TOKEN',
                required: true,
                value: 'VERCEL_TOKEN',
            },
        ],
    },
    'semantic-release': {
        id: 'semantic-release',
        runner: 'ubuntu-latest',
        jobName: 'release',
        name: 'Automated releasing with Semantic Release',
        description: 'Automate versioning, changelog generation, and releases with semantic-release on every push.',
        filename: 'semantic-release.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'Releasing with Semantic Release',
                required: true,
                value: 'Releasing with Semantic Release',
            },
            {
                key: 'branch',
                label: 'Branch',
                type: 'input',
                placeholder: 'main',
                required: true,
                value: 'main',
            },
            {
                key: 'nodeVersion',
                label: 'Node.js version',
                type: 'select',
                required: true,
                options: ['16', '18', '20', '22'],
                default: '22',
                value: '22',
            },
            {
                key: 'installCommand',
                label: 'Install command',
                type: 'input',
                placeholder: 'npm install',
                required: true,
                value: 'npm install',
            },
            {
                key: 'buildCommand',
                label: 'Build command',
                type: 'input',
                placeholder: 'npm run build',
                required: true,
                value: 'npm run build',
            },
            {
                key: 'releaseCommand',
                label: 'Release command',
                type: 'input',
                placeholder: 'npx semantic-release',
                required: true,
                value: 'npx semantic-release',
            },
            {
                key: 'githubTokenSecret',
                label: 'GitHub token secret name',
                type: 'input',
                placeholder: 'GH_TOKEN',
                required: true,
                value: 'GH_TOKEN',
            },
        ],
    },
    'aws-s3-cloudfront-deploy': {
        id: 'aws-s3-cloudfront-deploy',
        runner: 'ubuntu-latest',
        jobName: 'deploy',
        name: 'Deploy to AWS S3 and CloudFront',
        description: 'Workflow to deploy a static site or frontend app to AWS S3 and invalidate CloudFront cache.',
        filename: 'aws-s3-cloudfront-deploy.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'AWS S3 and CloudFront Deployment',
                required: true,
                value: 'AWS S3 and CloudFront Deployment',
            },
            {
                key: 'branch',
                label: 'Branch',
                type: 'input',
                placeholder: 'main',
                required: true,
                value: 'main',
            },
            {
                key: 'nodeVersion',
                label: 'Node.js version',
                type: 'select',
                required: true,
                options: ['16', '18', '20', '22'],
                default: '22',
                value: '22',
            },
            {
                key: 'installCommand',
                label: 'Install command',
                type: 'input',
                placeholder: 'npm install',
                required: true,
                value: 'npm install',
            },
            {
                key: 'buildCommand',
                label: 'Build command',
                type: 'input',
                placeholder: 'npm run build',
                required: true,
                value: 'npm run build',
            },
            {
                key: 'awsRegionEnvironmentVariable',
                label: 'AWS Region environment variable name',
                type: 'input',
                placeholder: 'MY_AWS_REGION',
                required: true,
                value: 'MY_AWS_REGION',
            },
            {
                key: 'awsRegionEnvironmentVariableValue',
                label: 'AWS Region environment variable value',
                type: 'input',
                placeholder: '<YOUR AWS REGION>',
                required: true,
                value: '<YOUR AWS REGION>',
            },
            {
                key: 'awsRoleNameEnvironmentVariable',
                label: 'AWS Role Name environment variable name',
                type: 'input',
                placeholder: 'AWS_ROLENAME',
                required: true,
                value: 'AWS_ROLENAME',
            },
            {
                key: 'awsRoleNameEnvironmentVariableValue',
                label: 'AWS Role Name environment variable value',
                type: 'input',
                placeholder: '<YOUR AWS ROLE>',
                required: true,
                value: '<YOUR AWS ROLE>',
            },
            {
                // eslint-disable-next-line no-secrets/no-secrets
                key: 'awsS3BucketEnvironmentVariable',
                label: 'AWS S3 Bucket environment variable name',
                type: 'input',
                placeholder: 'AWS_S3_BUCKET',
                required: true,
                value: 'AWS_S3_BUCKET',
            },
            {
                // eslint-disable-next-line no-secrets/no-secrets
                key: 'awsS3BucketEnvironmentVariableValue',
                label: 'AWS S3 Bucket environment variable value',
                type: 'input',
                placeholder: '<YOUR S3 BUCKET>',
                required: true,
                value: '<YOUR S3 BUCKET>',
            },
            {
                key: 'sourceDirEnvironmentVariable',
                label: 'Source Directory environment variable name',
                type: 'input',
                placeholder: 'SOURCE_DIR',
                required: true,
                value: 'SOURCE_DIR',
            },
            {
                key: 'sourceDirEnvironmentVariableValue',
                label: 'Source Directory environment variable value',
                type: 'input',
                placeholder: './build',
                required: true,
                value: './build',
            },
            {
                key: 'cloudfrontDistributionIdSecret',
                label: 'CloudFront Distribution ID secret name',
                type: 'input',
                placeholder: 'CLOUDFRONT_DISTRIBUTION_ID',
                required: true,
                value: 'CLOUDFRONT_DISTRIBUTION_ID',
            },
            {
                key: 'awsAccountIdSecret',
                label: 'AWS Account ID secret name',
                type: 'input',
                placeholder: 'AWS_ACCOUNT_ID',
                required: true,
                value: 'AWS_ACCOUNT_ID',
            },
        ],
    },
    'security-scan-snyk': {
        id: 'security-scan-snyk',
        runner: 'ubuntu-latest',

        jobName: 'snyk-scan',
        name: 'Security scan with Snyk',
        description: 'Scan project dependencies for vulnerabilities using Snyk.',
        filename: 'security-scan-snyk.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'Snyk Security Scan',
                required: true,
                value: 'Snyk Security Scan',
            },
            {
                key: 'branch',
                label: 'Branch',
                type: 'input',
                placeholder: 'main',
                required: true,
                value: 'main',
            },
            {
                key: 'snykCodeStack',
                label: 'Snyk code stack',
                type: 'select',
                required: true,
                options: ['Dotnet', 'Golang', 'Gradle', 'Maven', 'Node', 'PHP', 'Python', 'Ruby'],
                default: 'Node',
                value: 'Node',
            },
            {
                key: 'snykSeverityThreshold',
                label: 'Severity threshold',
                type: 'select',
                required: true,
                options: ['low', 'medium', 'high'],
                default: 'high',
                value: 'high',
            },
            {
                key: 'snykTokenSecret',
                label: 'Snyk token secret name',
                type: 'input',
                placeholder: 'SNYK_TOKEN',
                required: true,
                value: 'SNYK_TOKEN',
            },
        ],
    },
    'docker-image-publish': {
        id: 'docker-image-publish',
        runner: 'ubuntu-latest',
        jobName: 'docker-publish',
        name: 'Publish Docker image',
        description: 'Workflow to build and publish a Docker image to a container registry.',
        filename: 'docker-image-publish.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'Publish Docker Image',
                required: true,
                value: 'Publish Docker Image',
            },
            {
                key: 'branch',
                label: 'Branch',
                type: 'input',
                placeholder: 'main',
                required: true,
                value: 'main',
            },
            {
                key: 'dockerRegistry',
                label: 'Docker registry',
                type: 'select',
                options: ['Docker', 'Github Container Registry'],
                placeholder: 'Docker',
                required: true,
                value: 'Docker',
            },
            {
                key: 'dockerUsername',
                label: 'Docker Hub username',
                type: 'input',
                placeholder: '<YOUR_DOCKER_USERNAME>',
                required: true,
                value: '<YOUR_DOCKER_USERNAME>',
            },
            {
                key: 'dockerPasswordSecret',
                label: 'Docker Hub password secret name',
                type: 'input',
                placeholder: 'DOCKER_PASSWORD',
                required: true,
                value: 'DOCKER_PASSWORD',
            },
            {
                key: 'dockerBuildContext',
                label: 'Docker build context',
                type: 'input',
                placeholder: '.',
                required: true,
                value: '.',
            },
            {
                key: 'dockerDockerfile',
                label: 'Dockerfile',
                type: 'input',
                placeholder: 'Dockerfile',
                required: true,
                value: 'Dockerfile',
            },
            {
                key: 'dockerImageTags',
                label: 'Docker image tags (comma separated)',
                type: 'input',
                placeholder: 'latest',
                required: true,
                value: 'latest',
            },
        ],
    },
    'auto-tag-version': {
        id: 'auto-tag-version',
        runner: 'ubuntu-latest',
        jobName: 'auto-tag',
        name: 'Auto Tag Version',
        description: 'Automatically tag the version based on version file.',
        filename: 'auto-tag-version.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'Auto Tag Version',
                required: true,
                value: 'Auto Tag Version',
            },
            {
                key: 'autoTagVersionCommand',
                label: 'Version command',
                type: 'input',
                placeholder: 'cat current-version.txt',
                required: true,
                value: 'cat current-version.txt',
            },
        ],
    },
    'laravel-forge-deploy': {
        id: 'laravel-forge-deploy',
        runner: 'ubuntu-latest',
        jobName: 'laravel-forge-deploy',
        name: 'Laravel Forge deployment',
        description: 'Deploy a Laravel application to a Laravel Forge-managed server on push events.',
        filename: 'laravel-forge-deploy.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'Laravel Forge Deployment',
                required: true,
                value: 'Laravel Forge Deployment',
            },
            {
                key: 'branch',
                label: 'Branch',
                type: 'input',
                placeholder: 'main',
                required: true,
                value: 'main',
            },
            {
                key: 'deployMode',
                label: 'Deployment mode',
                type: 'select',
                required: true,
                options: ['webhook', 'api'],
                default: 'webhook',
                value: 'webhook',
            },
            {
                key: 'laravelForgeDeployTriggerUrlSecretName',
                label: 'Trigger URL secret name',
                type: 'input',
                placeholder: 'LARAVEL_FORGE_TRIGGER_URL',
                required: true,
                value: 'LARAVEL_FORGE_TRIGGER_URL',
            },
            {
                key: 'laravelForgeDeployApiKeySecretName',
                label: 'API Key secret name',
                type: 'input',
                placeholder: 'LARAVEL_FORGE_API_KEY',
                required: true,
                value: 'LARAVEL_FORGE_API_KEY',
            },
            {
                key: 'laravelForgeDeployServerIdSecretName',
                label: 'Server ID secret name',
                type: 'input',
                placeholder: 'LARAVEL_FORGE_SERVER_ID',
                required: true,
                value: 'LARAVEL_FORGE_SERVER_ID',
            },
            {
                key: 'laravelForgeDeploySiteIdSecretName',
                label: 'Site ID secret name',
                type: 'input',
                placeholder: 'LARAVEL_FORGE_SITE_ID',
                required: true,
                value: 'LARAVEL_FORGE_SITE_ID',
            },
        ],
    },
};
