import { WorkflowTemplateConfig } from '@octolab/domain';

/**
 * Default configurations for template workflows.
 */
export const workflowsDefaultConfigs: Record<string, WorkflowTemplateConfig> = {
    'node-pr-verify': {
        id: 'node-pr-verify',
        runner: 'ubuntu-latest',
        jobName: 'verify',
        name: 'Node.js pull request verify',
        description: 'Workflow to check the quality of a pull request in a Node.js stack.',
        filename: 'node-pr-verify.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'Node.js pull request verify',
                required: true,
                value: 'Node.js pull request verify',
                yamlPath: 'name',
            },
            {
                key: 'nodeVersion',
                label: 'Node.js version',
                type: 'select',
                required: true,
                options: ['16', '18', '20', '22'],
                default: '22',
                value: '22',
                yamlPath: 'jobs.verify.steps[1].with.node-version',
            },
            {
                key: 'installCommand',
                label: 'Install command',
                type: 'input',
                placeholder: 'npm install',
                required: true,
                value: 'npm install',
                helpMessage: 'Consider using `npm ci` for faster and more reliable builds.',
                yamlPath: 'jobs.verify.steps[2].run',
            },
            {
                key: 'lintCommand',
                label: 'Lint command',
                type: 'input',
                placeholder: 'npm run lint',
                required: true,
                value: 'npm run lint',
                yamlPath: 'jobs.verify.steps[3].run',
            },
            {
                key: 'testCommand',
                label: 'Test command',
                type: 'input',
                placeholder: 'npm run test',
                required: true,
                value: 'npm run test',
                yamlPath: 'jobs.verify.steps[4].run',
            },
            {
                key: 'buildCommand',
                label: 'Build command',
                type: 'input',
                placeholder: 'npm run build',
                required: true,
                value: 'npm run build',
                yamlPath: 'jobs.verify.steps[5].run',
            },
        ],
    },
    'nx-pr-verify': {
        id: 'nx-pr-verify',
        runner: 'ubuntu-latest',
        jobName: 'verify',
        name: 'NX pull request verify',
        description: 'Workflow to check the quality of a pull request in a NX monorepo.',
        filename: 'nx-pr-verify.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'NX Pull request verify',
                required: true,
                value: 'NX Pull request verify',
                yamlPath: 'name',
            },
            {
                key: 'baseBranch',
                label: 'Base branch',
                type: 'input',
                placeholder: 'main',
                required: true,
                value: 'main',
                yamlPath: 'baseBranch',
            },
            {
                key: 'nodeVersion',
                label: 'Node.js version',
                type: 'select',
                required: true,
                options: ['16', '18', '20', '22'],
                default: '22',
                value: '22',
                yamlPath: 'jobs.verify.steps[1].with.node-version',
            },
            {
                key: 'installCommand',
                label: 'Install command',
                type: 'input',
                placeholder: 'npm install',
                required: true,
                value: 'npm install',
                helpMessage: 'Consider using `npm ci` for faster and more reliable builds.',
                yamlPath: 'jobs.verify.steps[2].run',
            },
            {
                key: 'lintCommand',
                label: 'Lint command',
                type: 'input',
                placeholder: 'npx nx affected --target=lint --head=HEAD',
                required: true,
                value: 'npx nx affected --target=lint --head=HEAD',
                yamlPath: 'jobs.verify.steps[3].run',
            },
            {
                key: 'testCommand',
                label: 'Test command',
                type: 'input',
                placeholder: 'npx nx affected --target=test --head=HEAD',
                required: true,
                value: 'npx nx affected --target=test --head=HEAD',
                yamlPath: 'jobs.verify.steps[4].run',
            },
            {
                key: 'buildCommand',
                label: 'Build command',
                type: 'input',
                placeholder: 'npx nx affected --target=build --head=HEAD',
                required: true,
                value: 'npx nx affected --target=build --head=HEAD',
                yamlPath: 'jobs.verify.steps[5].run',
            },
        ],
    },
    'npm-publish': {
        id: 'npm-publish',
        runner: 'ubuntu-latest',
        jobName: 'publish',
        name: 'Publish to NPM',
        description: 'Workflow to publish a package in NPM.',
        filename: 'npm-publish.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'Publish to NPM',
                required: true,
                value: 'Publish to NPM',
                yamlPath: 'name',
            },
            {
                key: 'branch',
                label: 'Branch',
                type: 'input',
                placeholder: 'main',
                required: true,
                value: 'main',
                yamlPath: 'on.push.branches[0]',
            },
            {
                key: 'nodeVersion',
                label: 'Node.js version',
                type: 'select',
                required: true,
                options: ['16', '18', '20', '22'],
                default: '22',
                value: '22',
                yamlPath: 'jobs.publish.steps[1].with.node-version',
            },
            {
                key: 'installCommand',
                label: 'Install command',
                type: 'input',
                placeholder: 'npm install',
                required: true,
                value: 'npm install',
                helpMessage: 'Consider using `npm ci` for faster and more reliable builds.',
                yamlPath: 'jobs.publish.steps[2].run',
            },
            {
                key: 'testCommand',
                label: 'Test command',
                type: 'input',
                placeholder: 'npm run test',
                required: true,
                value: 'npm run test',
                yamlPath: 'jobs.publish.steps[3].run',
            },
            {
                key: 'buildCommand',
                label: 'Build command',
                type: 'input',
                placeholder: 'npm run build',
                required: true,
                value: 'npm run build',
                yamlPath: 'jobs.publish.steps[4].run',
            },
            {
                key: 'npmTokenSecret',
                label: 'NPM token secret name',
                type: 'input',
                placeholder: 'NPM_TOKEN',
                required: true,
                value: 'NPM_TOKEN',
                helpMessage: 'Make sure you have created the secret in your repository configuration.',
                yamlPath: 'jobs.publish.steps[5].with.token',
            },
        ],
    },
    'vercel-pro-deployment': {
        id: 'vercel-pro-deployment',
        runner: 'ubuntu-latest',
        jobName: 'deploy',
        name: 'Vercel production deployment',
        description: 'Deploy a productive application to Vercel',
        filename: 'vercel-pro-deployment.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'Vercel PRO deployment',
                required: true,
                value: 'Vercel PRO deployment',
                yamlPath: 'name',
            },
            {
                key: 'branch',
                label: 'Branch',
                type: 'input',
                placeholder: 'main',
                required: true,
                value: 'main',
                yamlPath: 'on.push.branches[0]',
            },
            {
                key: 'vercelTokenSecret',
                label: 'Vercel token secret name',
                type: 'input',
                placeholder: 'VERCEL_TOKEN',
                required: true,
                value: 'VERCEL_TOKEN',
                helpMessage: 'Make sure you have created the secret in your repository configuration.',
            },
        ],
    },
    'semantic-release': {
        id: 'semantic-release',
        runner: 'ubuntu-latest',
        jobName: 'release',
        name: 'Automated releasing with Semantic Release',
        description: 'Automate versioning, changelog generation, and releases with semantic-release on every push.',
        filename: 'semantic-release.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'Releasing with Semantic Release',
                required: true,
                value: 'Releasing with Semantic Release',
                yamlPath: 'name',
            },
            {
                key: 'branch',
                label: 'Branch',
                type: 'input',
                placeholder: 'main',
                required: true,
                value: 'main',
                yamlPath: 'on.push.branches[0]',
            },
            {
                key: 'nodeVersion',
                label: 'Node.js version',
                type: 'select',
                required: true,
                options: ['16', '18', '20', '22'],
                default: '22',
                value: '22',
                yamlPath: 'jobs.release.steps[1].with.node-version',
            },
            {
                key: 'installCommand',
                label: 'Install command',
                type: 'input',
                placeholder: 'npm install',
                required: true,
                value: 'npm install',
                helpMessage: 'Consider using `npm ci` for faster and more reliable builds.',
                yamlPath: 'jobs.release.steps[2].run',
            },
            {
                key: 'buildCommand',
                label: 'Build command',
                type: 'input',
                placeholder: 'npm run build',
                required: true,
                value: 'npm run build',
                yamlPath: 'jobs.release.steps[3].run',
            },
            {
                key: 'releaseCommand',
                label: 'Release command',
                type: 'input',
                placeholder: 'npx semantic-release',
                required: true,
                value: 'npx semantic-release',
                yamlPath: 'jobs.release.steps[4].run',
            },
            {
                key: 'githubTokenSecret',
                label: 'GitHub token secret name',
                type: 'input',
                placeholder: 'GH_TOKEN',
                required: true,
                value: 'GH_TOKEN',
                helpMessage: 'You can use the default Github token or set your own.',
                yamlPath: 'jobs.release.steps[4].env.GITHUB_TOKEN',
            },
        ],
    },
    'aws-s3-cloudfront-deploy': {
        id: 'aws-s3-cloudfront-deploy',
        runner: 'ubuntu-latest',
        jobName: 'deploy',
        name: 'Deploy to AWS S3 and CloudFront',
        description: 'Workflow to deploy a static site or frontend app to AWS S3 and invalidate CloudFront cache.',
        filename: 'aws-s3-cloudfront-deploy.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'AWS S3 and CloudFront Deployment',
                required: true,
                value: 'AWS S3 and CloudFront Deployment',
                yamlPath: 'name',
            },
            {
                key: 'branch',
                label: 'Branch',
                type: 'input',
                placeholder: 'main',
                required: true,
                value: 'main',
                yamlPath: 'on.push.branches[0]',
            },
            {
                key: 'nodeVersion',
                label: 'Node.js version',
                type: 'select',
                required: true,
                options: ['16', '18', '20', '22'],
                default: '22',
                value: '22',
                yamlPath: 'jobs.deploy.steps[1].with.node-version',
            },
            {
                key: 'installCommand',
                label: 'Install command',
                type: 'input',
                placeholder: 'npm install',
                required: true,
                value: 'npm install',
                helpMessage: 'Consider using `npm ci` for faster and more reliable builds.',
                yamlPath: 'jobs.deploy.steps[2].run',
            },
            {
                key: 'buildCommand',
                label: 'Build command',
                type: 'input',
                placeholder: 'npm run build',
                required: true,
                value: 'npm run build',
                yamlPath: 'jobs.deploy.steps[3].run',
            },
            {
                key: 'awsRegionEnvironmentVariable',
                label: 'AWS Region environment variable name',
                type: 'input',
                placeholder: 'MY_AWS_REGION',
                required: true,
                value: 'MY_AWS_REGION',
                yamlPath: 'env.MY_AWS_REGION',
            },
            {
                key: 'awsRegionEnvironmentVariableValue',
                label: 'AWS Region environment variable value',
                type: 'input',
                placeholder: '<YOUR AWS REGION>',
                required: true,
                value: '<YOUR AWS REGION>',
                yamlPath: 'env.MY_AWS_REGION',
            },
            {
                key: 'awsRoleNameEnvironmentVariable',
                label: 'AWS Role Name environment variable name',
                type: 'input',
                placeholder: 'AWS_ROLENAME',
                required: true,
                value: 'AWS_ROLENAME',
                yamlPath: 'env.AWS_ROLENAME',
            },
            {
                key: 'awsRoleNameEnvironmentVariableValue',
                label: 'AWS Role Name environment variable value',
                type: 'input',
                placeholder: '<YOUR AWS ROLE>',
                required: true,
                value: '<YOUR AWS ROLE>',
                yamlPath: 'env.AWS_ROLENAME',
            },
            {
                // eslint-disable-next-line no-secrets/no-secrets
                key: 'awsS3BucketEnvironmentVariable',
                label: 'AWS S3 Bucket environment variable name',
                type: 'input',
                placeholder: 'AWS_S3_BUCKET',
                required: true,
                value: 'AWS_S3_BUCKET',
                yamlPath: 'env.AWS_S3_BUCKET',
            },
            {
                // eslint-disable-next-line no-secrets/no-secrets
                key: 'awsS3BucketEnvironmentVariableValue',
                label: 'AWS S3 Bucket environment variable value',
                type: 'input',
                placeholder: '<YOUR S3 BUCKET>',
                required: true,
                value: '<YOUR S3 BUCKET>',
                yamlPath: 'env.AWS_S3_BUCKET',
            },
            {
                key: 'sourceDirEnvironmentVariable',
                label: 'Source Directory environment variable name',
                type: 'input',
                placeholder: 'SOURCE_DIR',
                required: true,
                value: 'SOURCE_DIR',
                yamlPath: 'env.SOURCE_DIR',
            },
            {
                key: 'sourceDirEnvironmentVariableValue',
                label: 'Source Directory environment variable value',
                type: 'input',
                placeholder: './build',
                required: true,
                value: './build',
                yamlPath: 'env.SOURCE_DIR',
            },
            {
                key: 'cloudfrontDistributionIdSecret',
                label: 'CloudFront Distribution ID secret name',
                type: 'input',
                placeholder: 'CLOUDFRONT_DISTRIBUTION_ID',
                required: true,
                value: 'CLOUDFRONT_DISTRIBUTION_ID',
                helpMessage: 'Make sure you have created the secret in your repository configuration.',
                yamlPath: 'jobs.deploy.steps[6].run',
            },
            {
                key: 'awsAccountIdSecret',
                label: 'AWS Account ID secret name',
                type: 'input',
                placeholder: 'AWS_ACCOUNT_ID',
                required: true,
                value: 'AWS_ACCOUNT_ID',
                helpMessage: 'Make sure you have created the secret in your repository configuration.',
                yamlPath: 'jobs.deploy.steps[4].with.role-to-assume',
            },
        ],
    },
    'security-scan-snyk': {
        id: 'security-scan-snyk',
        runner: 'ubuntu-latest',

        jobName: 'snyk-scan',
        name: 'Security scan with Snyk',
        description: 'Scan project dependencies for vulnerabilities using Snyk.',
        filename: 'security-scan-snyk.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'Snyk Security Scan',
                required: true,
                value: 'Snyk Security Scan',
                yamlPath: 'name',
            },
            {
                key: 'branch',
                label: 'Branch',
                type: 'input',
                placeholder: 'main',
                required: true,
                value: 'main',
                yamlPath: 'on.push.branches[0]',
            },
            {
                key: 'snykCodeStack',
                label: 'Snyk code stack',
                type: 'select',
                required: true,
                options: ['Dotnet', 'Golang', 'Gradle', 'Maven', 'Node', 'PHP', 'Python', 'Ruby'],
                default: 'Node',
                value: 'Node',
                yamlPath: 'jobs.snyk-scan.steps[1].uses',
            },
            {
                key: 'snykSeverityThreshold',
                label: 'Severity threshold',
                type: 'select',
                required: true,
                options: ['low', 'medium', 'high'],
                default: 'high',
                value: 'high',
                yamlPath: 'jobs.snyk-scan.steps[1].with.args',
            },
            {
                key: 'snykTokenSecret',
                label: 'Snyk token secret name',
                type: 'input',
                placeholder: 'SNYK_TOKEN',
                required: true,
                value: 'SNYK_TOKEN',
                helpMessage: 'Make sure you have created the secret in your repository configuration.',
                yamlPath: 'jobs.snyk-scan.steps[1].env.SNYK_TOKEN',
            },
        ],
    },
    'docker-image-publish': {
        id: 'docker-image-publish',
        runner: 'ubuntu-latest',
        jobName: 'docker-publish',
        name: 'Publish Docker image',
        description: 'Workflow to build and publish a Docker image to a container registry.',
        filename: 'docker-image-publish.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'Publish Docker Image',
                required: true,
                value: 'Publish Docker Image',
                yamlPath: 'name',
            },
            {
                key: 'branch',
                label: 'Branch',
                type: 'input',
                placeholder: 'main',
                required: true,
                value: 'main',
                yamlPath: 'on.push.branches[0]',
            },
            {
                key: 'dockerRegistry',
                label: 'Docker registry',
                type: 'select',
                options: ['Docker', 'Github Container Registry'],
                placeholder: 'Docker',
                required: true,
                value: 'Docker',
                yamlPath: 'jobs.docker-publish.steps[0].with.registry',
            },
            {
                key: 'dockerUsername',
                label: 'Docker Hub username',
                type: 'input',
                placeholder: '<YOUR_DOCKER_USERNAME>',
                required: true,
                value: '<YOUR_DOCKER_USERNAME>',
                yamlPath: 'jobs.docker-publish.steps[0].with.username',
            },
            {
                key: 'dockerPasswordSecret',
                label: 'Docker Hub password secret name',
                type: 'input',
                placeholder: 'DOCKER_PASSWORD',
                required: true,
                value: 'DOCKER_PASSWORD',
                helpMessage: 'Make sure you have created the secret in your repository configuration.',
                yamlPath: 'jobs.docker-publish.steps[0].with.password',
            },
            {
                key: 'dockerBuildContext',
                label: 'Docker build context',
                type: 'input',
                placeholder: '.',
                required: true,
                value: '.',
                yamlPath: 'jobs.docker-publish.steps[3].with.context',
            },
            {
                key: 'dockerDockerfile',
                label: 'Dockerfile',
                type: 'input',
                placeholder: 'Dockerfile',
                required: true,
                value: 'Dockerfile',
                yamlPath: 'jobs.docker-publish.steps[3].with.file',
            },
            {
                key: 'dockerImageTags',
                label: 'Docker image tags (comma separated)',
                type: 'input',
                placeholder: 'latest',
                required: true,
                value: 'latest',
                yamlPath: 'jobs.docker-publish.steps[3].with.tags',
            },
        ],
    },
    'auto-tag-version': {
        id: 'auto-tag-version',
        runner: 'ubuntu-latest',
        jobName: 'auto-tag',
        name: 'Auto Tag Version',
        description: 'Automatically tag the version based on version file.',
        filename: 'auto-tag-version.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'Auto Tag Version',
                required: true,
                value: 'Auto Tag Version',
                yamlPath: 'name',
            },
            {
                key: 'autoTagVersionCommand',
                label: 'Version command',
                type: 'input',
                placeholder: 'cat current-version.txt',
                required: true,
                value: 'cat current-version.txt',
                yamlPath: 'jobs.auto-tag.steps[1].with.version-command',
            },
        ],
    },
    'laravel-forge-deploy': {
        id: 'laravel-forge-deploy',
        runner: 'ubuntu-latest',
        jobName: 'laravel-forge-deploy',
        name: 'Laravel Forge deployment',
        description: 'Deploy a Laravel application to a Laravel Forge-managed server on push events.',
        filename: 'laravel-forge-deploy.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'Laravel Forge Deployment',
                required: true,
                value: 'Laravel Forge Deployment',
                yamlPath: 'name',
            },
            {
                key: 'branch',
                label: 'Branch',
                type: 'input',
                placeholder: 'main',
                required: true,
                value: 'main',
                yamlPath: 'on.push.branches[0]',
            },
            {
                key: 'deployMode',
                label: 'Deployment mode',
                type: 'select',
                required: true,
                options: ['webhook', 'api'],
                default: 'webhook',
                value: 'webhook',
            },
            {
                key: 'laravelForgeDeployTriggerUrlSecretName',
                label: 'Trigger URL secret name',
                type: 'input',
                placeholder: 'LARAVEL_FORGE_TRIGGER_URL',
                required: true,
                value: 'LARAVEL_FORGE_TRIGGER_URL',
                condition: {
                    field: 'deployMode',
                    equals: 'webhook',
                },
                helpMessage: 'Make sure you have created the secret in your repository configuration.',
                yamlPath: 'jobs.laravel-forge-deploy.steps[1].with.trigger-url',
            },
            {
                key: 'laravelForgeDeployApiKeySecretName',
                label: 'API Key secret name',
                type: 'input',
                placeholder: 'LARAVEL_FORGE_API_KEY',
                required: true,
                value: 'LARAVEL_FORGE_API_KEY',
                condition: {
                    field: 'deployMode',
                    equals: 'api',
                },
                helpMessage: 'Make sure you have created the secret in your repository configuration.',
                yamlPath: 'jobs.laravel-forge-deploy.steps[1].with.api_key',
            },
            {
                key: 'laravelForgeDeployServerIdSecretName',
                label: 'Server ID secret name',
                type: 'input',
                placeholder: 'LARAVEL_FORGE_SERVER_ID',
                required: true,
                value: 'LARAVEL_FORGE_SERVER_ID',
                condition: {
                    field: 'deployMode',
                    equals: 'api',
                },
                helpMessage: 'Make sure you have created the secret in your repository configuration.',
                yamlPath: 'jobs.laravel-forge-deploy.steps[1].with.server_id',
            },
            {
                key: 'laravelForgeDeploySiteIdSecretName',
                label: 'Site ID secret name',
                type: 'input',
                placeholder: 'LARAVEL_FORGE_SITE_ID',
                required: true,
                value: 'LARAVEL_FORGE_SITE_ID',
                condition: {
                    field: 'deployMode',
                    equals: 'api',
                },
                helpMessage: 'Make sure you have created the secret in your repository configuration.',
                yamlPath: 'jobs.laravel-forge-deploy.steps[1].with.site_id',
            },
        ],
    },
    'pr-conventional-commit-checker': {
        id: 'pr-conventional-commit-checker',
        runner: 'ubuntu-latest',
        jobName: 'commit-lint',
        name: 'Pull Request Conventional Commit checker',
        description: 'Workflow to ensure all commits in a pull request follow the Conventional Commits specification.',
        filename: 'pr-conventional-commit-checker.yml',
        fields: [
            {
                key: 'workflowName',
                label: 'Name',
                type: 'input',
                placeholder: 'Conventional Commit PR Validator',
                required: true,
                value: 'Conventional Commit PR Validator',
                yamlPath: 'name',
            },
            {
                key: 'targetBranch',
                label: 'Target branch',
                type: 'input',
                placeholder: '${{ github.event.pull_request.base.ref }}',
                required: true,
                value: '${{ github.event.pull_request.base.ref }}',
                helpMessage: 'The branch into which the pull request is being merged.',
                yamlPath: 'jobs.commit-lint.steps[1].with.target-branch',
            },
            {
                key: 'currentBranch',
                label: 'Current branch',
                type: 'input',
                placeholder: '${{ github.event.pull_request.head.ref }}',
                required: true,
                value: '${{ github.event.pull_request.head.ref }}',
                helpMessage: 'The branch from which the pull request originates.',
                yamlPath: 'jobs.commit-lint.steps[1].with.current-branch',
            },
            {
                key: 'commitLintPattern',
                label: 'Commit check pattern',
                type: 'input',
                placeholder: '(feat|fix|ci|chore|docs|test|style|refactor): .{1,}$',
                required: true,
                value: '(feat|fix|ci|chore|docs|test|style|refactor): .{1,}$',
                helpMessage: 'Regular expression to validate commit messages',
                yamlPath: 'jobs.commit-lint.steps[1].with.commit-lint-pattern',
            },
        ],
    },
};
