import { WorkflowConfig } from '@octolab/domain';

/**
 * Default configurations for each workflow.
 */
export const workflowsDefaultConfigs: Record<string, WorkflowConfig> = {
    'npm-publish': {
        id: 'npm-publish',
        runner: 'ubuntu-latest',
        branch: 'main',
        nodeVersion: '22',
        installCommand: 'npm install',
        testCommand: 'npm run test',
        buildCommand: 'npm run build',
        npmTokenSecret: 'NPM_TOKEN',
        workflowName: 'Publish to NPM',
        jobName: 'publish',
        name: 'Publish to NPM',
        description: 'Workflow to publish a package in NPM.',
        filename: 'npm-publish.yml',
    },
    'node-pr-verify': {
        id: 'node-pr-verify',
        runner: 'ubuntu-latest',
        nodeVersion: '22',
        installCommand: 'npm install',
        lintCommand: 'npm run lint',
        testCommand: 'npm run test',
        buildCommand: 'npm run build',
        workflowName: 'Node.js Pull request verify',
        jobName: 'verify',
        name: 'Node.js pull request verify',
        description: 'Workflow to check the quality of a pull request in a Node.js stack.',
        filename: 'node-pr-verify.yml',
    },
    'nx-pr-verify': {
        id: 'nx-pr-verify',
        runner: 'ubuntu-latest',
        nodeVersion: '22',
        baseBranch: 'main',
        installCommand: 'npm install',
        lintCommand: 'npx nx affected --target=lint --head=HEAD',
        testCommand: 'npx nx affected --target=test --head=HEAD',
        buildCommand: 'npx nx affected --target=build --head=HEAD',
        workflowName: 'NX Pull request verify',
        jobName: 'verify',
        name: 'NX pull request verify',
        description: 'Workflow to check the quality of a pull request in a NX monorepo.',
        filename: 'nx-pr-verify.yml',
    },
    'vercel-pro-deployment': {
        id: 'vercel-pro-deployment',
        runner: 'ubuntu-latest',
        jobName: 'deploy',
        branch: 'main',
        workflowName: 'Vercel PRO deployment',
        vercelTokenSecret: 'VERCEL_TOKEN',
        name: 'Vercel production deployment',
        description: 'Deploy a productive application to Vercel',
        filename: 'vercel-pro-deployment.yml',
    },
    'semantic-release': {
        id: 'semantic-release',
        runner: 'ubuntu-latest',
        branch: 'main',
        nodeVersion: '22',
        installCommand: 'npm install',
        buildCommand: 'npm run build',
        releaseCommand: 'npx semantic-release',
        githubTokenSecret: 'GH_TOKEN',
        workflowName: 'Semantic Release',
        jobName: 'release',
        name: 'Automated releasing with Semantic Release',
        description: 'Automate versioning, changelog generation, and releases with semantic-release on every push.',
        filename: 'semantic-release.yml',
    },
    'aws-s3-cloudfront-deploy': {
        id: 'aws-s3-cloudfront-deploy',
        runner: 'ubuntu-latest',
        branch: 'main',
        nodeVersion: '22',
        installCommand: 'npm install',
        buildCommand: 'npm run build',
        awsRegionEnvironmentVariable: 'MY_AWS_REGION',
        awsRegionEnvironmentVariableValue: '<YOUR AWS REGION>',
        awsRoleNameEnvironmentVariable: 'AWS_ROLENAME',
        awsRoleNameEnvironmentVariableValue: '<YOUR AWS ROLE>',
        awsS3BucketEnvironmentVariable: 'AWS_S3_BUCKET',
        awsS3BucketEnvironmentVariableValue: '<YOUR S3 BUCKET>',
        sourceDirEnvironmentVariable: 'SOURCE_DIR',
        sourceDirEnvironmentVariableValue: './build',
        cloudfrontDistributionIdSecret: 'CLOUDFRONT_DISTRIBUTION_ID',
        awsAccountIdSecret: 'AWS_ACCOUNT_ID',
        workflowName: 'AWS S3 and CloudFront Deployment',
        jobName: 'deploy',
        name: 'Deploy to AWS S3 and CloudFront',
        description: 'Workflow to deploy a static site or frontend app to AWS S3 and invalidate CloudFront cache.',
        filename: 'aws-s3-cloudfront-deploy.yml',
    },
    'security-scan-snyk': {
        id: 'security-scan-snyk',
        runner: 'ubuntu-latest',
        branch: 'main',
        snykCodeStack: 'Node',
        snykSeverityThreshold: 'high',
        snykTokenSecret: 'SNYK_TOKEN',
        workflowName: 'Snyk Security Scan',
        jobName: 'snyk-scan',
        name: 'Security scan with Snyk',
        description: 'Scan project dependencies for vulnerabilities using Snyk.',
        filename: 'security-scan-snyk.yml',
    },
};
