/**
 * Terms of Use page
 */
export default function TermsPage() {
    const contactEmail = process.env.CONTACT_EMAIL;

    return (
        <main className="p-8 max-w-3xl mx-auto">
            <h1 className="text-3xl font-bold mb-12 mt-4 text-center">Terms of Use</h1>

            <div className="text-text-muted space-y-6 text-lg">
                <p>
                    By using <strong className="text-text">OctoLab</strong>, you agree to the following{' '}
                    <span className="text-primary font-semibold">terms and conditions of use</span>. We recommend that you read them carefully before proceeding.
                </p>

                <h2 className="text-2xl font-semibold text-text">1. Acceptance of Terms</h2>
                <p>By accessing and using OctoLab, you agree to be bound by these Terms of Use. If you do not agree with any part of them, please do not use the application.</p>

                <h2 className="text-2xl font-semibold text-text">2. Service Description</h2>
                <p>
                    OctoLab is an online platform that allows developers to visually design and manage GitHub Actions workflows. The service is currently in beta and may change
                    without prior notice.
                </p>

                <h2 className="text-2xl font-semibold text-text">3. Acceptable Use</h2>
                <p>By using OctoLab, you agree to:</p>
                <ul className="list-disc pl-6 space-y-1 mt-2">
                    <li>Not use the service for any illegal or unauthorized purposes.</li>
                    <li>Not interfere with the functionality, security, or stability of the platform.</li>
                    <li>Not attempt to access other users’ accounts or data without permission.</li>
                </ul>

                <h2 className="text-2xl font-semibold text-text">4. Intellectual Property</h2>
                <p>
                    All content, design, and technical infrastructure of OctoLab are the property of its creators. Workflows generated by users remain their own property, although
                    OctoLab may analyze them in an <span className="text-primary font-semibold">aggregated and anonymized</span> way to improve the product.
                </p>

                <h2 className="text-2xl font-semibold text-text">5. Limitation of Liability</h2>
                <p>
                    OctoLab is provided &ldquo;as is&quot; and we do not guarantee uninterrupted availability, accuracy, or suitability for any specific purpose. We are not liable
                    for loss or damage arising from the use of the service.
                </p>

                <h2 className="text-2xl font-semibold text-text">6. Modifications</h2>
                <p>We reserve the right to modify these terms at any time. If significant changes are made, we will notify users via the app or by email, if applicable.</p>

                <h2 className="text-2xl font-semibold text-text">7. Contact</h2>
                <p>
                    If you have any questions about these Terms of Use, feel free to contact us at{' '}
                    <a href={`mailto:${contactEmail}`} className="text-primary hover:underline">
                        {contactEmail}
                    </a>
                    .
                </p>

                <p className="font-medium text-text">Thank you for trusting OctoLab to power your automation workflows. 🚀</p>
            </div>
        </main>
    );
}
